USE MASTER
GO
EXEC master.dbo.xp_create_subdir 'D:\SalesTrackingSystem\Database'
GO
DROP DATABASE IF EXISTS SalesTrackingSystem
GO
USE MASTER
GO
CREATE DATABASE [SalesTrackingSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SalesTrackingSystem', FILENAME = N'D:\SalesTrackingSystem\Database\SalesTrackingSystem.mdf' , SIZE = 10240KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SalesTrackingSystem_log', FILENAME = N'D:\SalesTrackingSystem\Database\SalesTrackingSystem_log.ldf' , SIZE = 10240KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [SalesTrackingSystem] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [SalesTrackingSystem] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SalesTrackingSystem] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SalesTrackingSystem] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SalesTrackingSystem] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SalesTrackingSystem] SET ARITHABORT OFF 
GO
ALTER DATABASE [SalesTrackingSystem] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SalesTrackingSystem] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SalesTrackingSystem] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [SalesTrackingSystem] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SalesTrackingSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SalesTrackingSystem] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SalesTrackingSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SalesTrackingSystem] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SalesTrackingSystem] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SalesTrackingSystem] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SalesTrackingSystem] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SalesTrackingSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SalesTrackingSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SalesTrackingSystem] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SalesTrackingSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SalesTrackingSystem] SET  READ_WRITE 
GO
ALTER DATABASE [SalesTrackingSystem] SET RECOVERY FULL 
GO
ALTER DATABASE [SalesTrackingSystem] SET  MULTI_USER 
GO
ALTER DATABASE [SalesTrackingSystem] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SalesTrackingSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SalesTrackingSystem] SET DELAYED_DURABILITY = DISABLED 
GO
USE [SalesTrackingSystem]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [SalesTrackingSystem]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [SalesTrackingSystem] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
