//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public long BatchID { get; set; }
        public string BatchName { get; set; }
        public Nullable<long> ProductCategoryId { get; set; }
        public decimal QunatityProduced { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<long> StockLeft { get; set; }
        public System.DateTime DateProduced { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<long> ProductID { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Product Product { get; set; }
    }
}
