//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardColumn
    {
        public long DashboardColumnId { get; set; }
        public Nullable<long> DashboardTableId { get; set; }
        public Nullable<long> DashboardID { get; set; }
        public Nullable<long> DashboardGivenColumnId { get; set; }
        public string Color { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual Dashboard Dashboard { get; set; }
        public virtual DashboardGivenColumn DashboardGivenColumn { get; set; }
        public virtual DashboardTable DashboardTable { get; set; }
    }
}
