//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dashboard()
        {
            this.DashboardColumns = new HashSet<DashboardColumn>();
        }
    
        public long DashboardID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> DashboardTableId { get; set; }
        public Nullable<long> DashboardTypeId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public bool ShowInHome { get; set; }
    
        public virtual DashboardTable DashboardTable { get; set; }
        public virtual DashboardType DashboardType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashboardColumn> DashboardColumns { get; set; }
    }
}
