//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SalesTrackingSystemEntities : DbContext
    {
        public SalesTrackingSystemEntities()
            : base("name=SalesTrackingSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<Dashboard> Dashboards { get; set; }
        public virtual DbSet<DashboardColumn> DashboardColumns { get; set; }
        public virtual DbSet<DashboardGivenColumn> DashboardGivenColumns { get; set; }
        public virtual DbSet<DashboardTable> DashboardTables { get; set; }
        public virtual DbSet<DashboardType> DashboardTypes { get; set; }
        public virtual DbSet<DistributorArea> DistributorAreas { get; set; }
        public virtual DbSet<Distributor> Distributors { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModuleAction> ModuleActions { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Reseller> Resellers { get; set; }
        public virtual DbSet<TransactionDetail> TransactionDetails { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserProfileDetail> UserProfileDetails { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Verification> Verifications { get; set; }
    
        public virtual ObjectResult<string> FetchMonth()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("FetchMonth");
        }
    
        public virtual ObjectResult<string> FetchYear()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("FetchYear");
        }
    
        public virtual ObjectResult<FetchReport_Result> FetchReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchReport_Result>("FetchReport");
        }
    
        public virtual ObjectResult<FetchMonthlyQuantity_Result> FetchMonthlyQuantity()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchMonthlyQuantity_Result>("FetchMonthlyQuantity");
        }
    }
}
