//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileDetail
    {
        public long UserProfileDetailID { get; set; }
        public Nullable<long> UserProfileID { get; set; }
        public Nullable<long> ModuleID { get; set; }
        public Nullable<long> ModuleActionID { get; set; }
        public Nullable<bool> ProfileDetailStatus { get; set; }
        public string Description { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual ModuleAction ModuleAction { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual User User { get; set; }
    }
}
