//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verification
    {
        public long VerificationID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.DateTime> DateVerified { get; set; }
        public string VerifiedToken { get; set; }
        public string ResetToken { get; set; }
        public Nullable<System.DateTime> ResetTriggered { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual User User { get; set; }
    }
}
